### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by That0neking** [SSPWXR0/weatherhds1#5]
Am I just dumb or is there no way of changing the locations? I went into the Config.cfg and put in my desired locations and got nothing. Also, I changed the Timezone to mine, EST and for some reason it's an hour behind. And when I tried to change the Units to Imperial all I got were undefined, I tried putting an I or Imperial in there and got nothing. I feel some documentation and instructions included would be nice. So please tell me how to solve these issues, please and thanks

**Comment by fdezwonders** [comment]
@That0neking 

>  I went into the Config.cfg and put in my desired locations and got nothing.

You have to wait ~10-20 seconds for all the location's data to get set up. (more or less secs depending on how many), after that, refresh and it should work.

> Also, I changed the Timezone to mine, EST and for some reason it's an hour behind.

It's set up to a nearest big city near you. For example, "America/Chicago" is for CDT. Ask chatgpt.com for more help.

> And when I tried to change the Units to Imperial all I got were undefined, I tried putting an I or Imperial in there and got nothing.

You change the unit to imperial by putting in "e" in "units".

> I feel some documentation and instructions included would be nice.

yes it would.

**Comment by That0neking** [comment]
Thanks mate! Decided to make a draft of the documentation as well, leaving this here to whomever may need it and so the dev can have it and improve upon it.
[Setup Help.txt](https://github.com/user-attachments/files/17385476/Setup.Help.txt)

**Comment by SSPWXR0** [comment]
Location fetching: True, after setting locations, you'll have to refresh the Node.js server since the actual weather fetching from the API is proxied through the Node server, then you refresh the browser.

Time zones: The timezone config uses data from tz database, standard with computer programs and operating systems.
You can view a list of time zones at this Wikipedia article: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Units: The input is as defined as TWC API: https://www.ibm.com/docs/en/environmental-intel-suite?topic=apis-weather-company-data-api-common-usage-guide#id__k9ghwen9fj7l__title__1

presentationType: This config setting defines what presentation would be displayed on screen, right now, there is the full presentation (0) and LDL-only mode (1). LDL-only would be used if there was actual programming video, and you want to overlay the weather information onto it. Like how The Weather Channel is during normal programming.

If there are any more things you would like me to clarify, or need help with, then feel free to ask me!

**Comment by fdezwonders** [comment]
@SSPWXR0 what does 'textureFiltering' mean?

**Comment by SSPWXR0** [comment]
basically if you want images to be pixelated or smooth when scaled. radar is forced to be always pixelated because i think it doesnt really look good when filtered.

i took the term "texture filtering" from video game graphics if you're wondering about that specifically.
